FROM amberframework/amber:0.33.0

RUN echo "Using Dockefile-production"

RUN apt-get update -qq -y
RUN apt-get install libsodium-dev -y

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs

WORKDIR /app

COPY shard.* /app/
RUN shards install

COPY . /app

ENV PATH="/app/node_modules/.bin:${PATH}"

RUN shards install --production
RUN shards build guest_control --release
RUN npm install .
# RUN yes | npm install webpack -g
# RUN yes | npm install webpack-cli -g
RUN yes | npm run release

RUN mkdir -p bin
RUN crystal build ./src/guest_control.cr -o bin/guest_control --release

CMD ./app-start.sh