FROM amberframework/amber:v0.31.0

RUN apt-get update -qq -y
RUN apt-get install libsodium-dev -y

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs

WORKDIR /app

COPY shard.* /app/
RUN shards install

COPY . /app

RUN npm install .
RUN npm run release
RUN shards install --production
RUN shards build guest_control --release

RUN mkdir -p bin
RUN crystal build ./src/guest_control.cr -o bin/guest_control --release --no-debug

CMD sh app-start.sh