FROM amberframework/amber:v0.32.0

RUN apt-get update -qq -y
RUN apt-get install libsodium-dev -y

WORKDIR /app

COPY shard.* /app/
RUN shards install

COPY . /app

RUN npm install . && npm run release
RUN shards install --production
RUN shards build guest_control --release

CMD bin/guest_control