defaults : &defaults
  host: db
  adapter: postgres
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  migration_files_path: db/migrations # this is the default location for all migrations

development:
  db: guest_control_development
  <<: *defaults

test:
  db: guest_control_test
  <<: *defaults

production:
  db: guest_control
  <<: *defaults